### ISSUE TITLE
test 模块单独运行报错

### ISSUE THREAD

**Issue by customEmotion** [kongxiaoan/component-api#1]
哈喽 test 模块单独运行报错，有什么解决办法吗

**Comment by kongxiaoan** [comment]
报什么错

**Comment by customEmotion** [comment]
FATAL EXCEPTION: main
                                                                                                    Process: com.kpa.test, PID: 27938
                                                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.kpa.test/com.kpa.test.TestActivity}: kotlin.UninitializedPropertyAccessException: lateinit property mUserService has not been initialized
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3869)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4011)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:111)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2466)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:240)
                                                                                                    	at android.os.Looper.loop(Looper.java:351)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8364)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
                                                                                                    Caused by: kotlin.UninitializedPropertyAccessException: lateinit property mUserService has not been initialized
                                                                                                    	at com.kpa.test.TestActivity.getMUserService(TestActivity.kt:17)
                                                                                                    	at com.kpa.test.TestActivity.onCreate(TestActivity.kt:23)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8397)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8370)### ###

**Comment by customEmotion** [comment]
不知道这咋弄  ，学习学习
